defaults:
  - finetune_config
  - _self_

do_overwrite: true
seed: 1
is_inference: true # Flag to indicate that this is an inference run
task_type: interruption # Task type for the inference run - used to use the appropirate evaluation metrics
threshold: 0.3

# Strategy:  (class dist)
load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield_final/finetuning/task_df_eneryield_interruption_7_day
task_df_name: task_df_eneryield_interruption_7_day
pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield_final/finetuning/task_df_eneryield_interruption_7_day/finetune_weights
config:
  is_cls_dist: false
  is_event_classification: false
  save_metrics: false
  is_interruption_forecast: true
  save_metrics_fp: /home/filip-marcus/results/eneryield_final/interruption_7_day_baseline


# # Strategy:  (class dist --> event label --> interruption in sequence --> interruption 3 day --> interruption 5 day --> interruption 7 day) 
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield_final/finetuning/task_df_eneryield_class_dist1/finetuning/task_df_eneryield_event_label1/finetuning/task_df_eneryield_interruption_in_seq1/finetuning/task_df_eneryield_interruption_3_day1/finetuning/task_df_eneryield_interruption_5_day1/finetuning/task_df_eneryield_interruption_7_day1
# task_df_name: task_df_eneryield_interruption_7_day1
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield_final/finetuning/task_df_eneryield_class_dist1/finetuning/task_df_eneryield_event_label1/finetuning/task_df_eneryield_interruption_in_seq1/finetuning/task_df_eneryield_interruption_3_day1/finetuning/task_df_eneryield_interruption_5_day1/finetuning/task_df_eneryield_interruption_7_day1/finetune_weights
# config:
#   is_cls_dist: false
#   is_event_classification: false
#   save_metrics: false
#   save_metrics_fp: /home/filip-marcus/results/eneryield_final/class_dist_event_label_interruption_in_seq_interruption3_interruption_5_day_interruption_7_day
#   is_interruption_forecast: true


# # Strategy:  (class dist --> interruption in sequence --> event label --> interruption 3 day --> interruption 5 day --> interruption 7 day) 
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield_final/finetuning/task_df_eneryield_class_dist1/finetuning/task_df_eneryield_interruption_in_seq1/finetuning/task_df_eneryield_event_label1/finetuning/task_df_eneryield_interruption_3_day1/finetuning/task_df_eneryield_interruption_5_day1/finetuning/task_df_eneryield_interruption_7_day1
# task_df_name: task_df_eneryield_interruption_7_day1
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield_final/finetuning/task_df_eneryield_class_dist1/finetuning/task_df_eneryield_interruption_in_seq1/finetuning/task_df_eneryield_event_label1/finetuning/task_df_eneryield_interruption_3_day1/finetuning/task_df_eneryield_interruption_5_day1/finetuning/task_df_eneryield_interruption_7_day1/finetune_weights
# config:
#   is_cls_dist: false
#   is_event_classification: false
#   save_metrics: false
#   save_metrics_fp: /home/filip-marcus/results/eneryield_final/class_dist_interruption_in_seq_event_label_interruption3_interruption5_interruption7
#   is_interruption_forecast: true

# # Strategy:  (event label --> class dist --> interruption in sequence --> interruption 3 day --> interruption 5 day --> interruption 7 day) 
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield_final/finetuning/task_df_eneryield_event_label1/finetuning/task_df_eneryield_class_dist1/finetuning/task_df_eneryield_interruption_in_seq1/finetuning/task_df_eneryield_interruption_3_day1/finetuning/task_df_eneryield_interruption_5_day1/finetuning/task_df_eneryield_interruption_7_day1
# task_df_name: task_df_eneryield_interruption_7_day1
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield_final/finetuning/task_df_eneryield_event_label1/finetuning/task_df_eneryield_class_dist1/finetuning/task_df_eneryield_interruption_in_seq1/finetuning/task_df_eneryield_interruption_3_day1/finetuning/task_df_eneryield_interruption_5_day1/finetuning/task_df_eneryield_interruption_7_day1/finetune_weights
# config:
#   is_cls_dist: false
#   is_event_classification: false
#   save_metrics: false
#   is_interruption_forecast: true
#   save_metrics_fp: /home/filip-marcus/results/eneryield_final/event_label_class_dist_interruption_in_seq_interruption3_interruption5_interruption7


# # Strategy:  (event label --> interruption in sequence --> class dist --> interruption 3 day --> interruption 5 day --> interruption 7 day) 
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield_final/finetuning/task_df_eneryield_event_label1/finetuning/task_df_eneryield_interruption_in_seq1/finetuning/task_df_eneryield_class_dist1/finetuning/task_df_eneryield_interruption_3_day1/finetuning/task_df_eneryield_interruption_5_day1/finetuning/task_df_eneryield_interruption_7_day1
# task_df_name: task_df_eneryield_interruption_7_day1
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield_final/finetuning/task_df_eneryield_event_label1/finetuning/task_df_eneryield_interruption_in_seq1/finetuning/task_df_eneryield_class_dist1/finetuning/task_df_eneryield_interruption_3_day1/finetuning/task_df_eneryield_interruption_5_day1/finetuning/task_df_eneryield_interruption_7_day1/finetune_weights
# config:
#   is_cls_dist: false
#   is_event_classification: false
#   save_metrics: false
#   is_interruption_forecast: true
#   save_metrics_fp: /home/filip-marcus/results/eneryield_final/event_label_interruption_in_seq_class_dist_interruption3_interruption5_interruption7


# # Strategy:  (interruption in seq --> class dist --> event label --> interruption 3 day --> interruption 5 day --> interruption 7 day) 
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield_final/finetuning/task_df_eneryield_interruption_in_seq1/finetuning/task_df_eneryield_class_dist1/finetuning/task_df_eneryield_event_label1/finetuning/task_df_eneryield_interruption_3_day1/finetuning/task_df_eneryield_interruption_5_day1/finetuning/task_df_eneryield_interruption_7_day1
# task_df_name: task_df_eneryield_interruption_7_day1
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield_final/finetuning/task_df_eneryield_interruption_in_seq1/finetuning/task_df_eneryield_class_dist1/finetuning/task_df_eneryield_event_label1/finetuning/task_df_eneryield_interruption_3_day1/finetuning/task_df_eneryield_interruption_5_day1/finetuning/task_df_eneryield_interruption_7_day1/finetune_weights
# config:
#   is_cls_dist: false
#   is_event_classification: false
#   save_metrics: false
#   is_interruption_forecast: true
#   save_metrics_fp: /home/filip-marcus/results/eneryield_final/interruption_in_seq_class_dist_event_label_interruption3_interruption5_interruption7

# # Strategy:  (interruption in seq --> event label --> class dist --> interruption 3 day --> interruption 5 day --> interruption 7 day) 
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield_final/finetuning/task_df_eneryield_interruption_in_seq1/finetuning/task_df_eneryield_event_label1/finetuning/task_df_eneryield_class_dist1/finetuning/task_df_eneryield_interruption_3_day1/finetuning/task_df_eneryield_interruption_5_day1/finetuning/task_df_eneryield_interruption_7_day1
# task_df_name: task_df_eneryield_interruption_7_day1
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield_final/finetuning/task_df_eneryield_interruption_in_seq1/finetuning/task_df_eneryield_event_label1/finetuning/task_df_eneryield_class_dist1/finetuning/task_df_eneryield_interruption_3_day1/finetuning/task_df_eneryield_interruption_5_day1/finetuning/task_df_eneryield_interruption_7_day1/finetune_weights
# config:
#   is_cls_dist: false
#   is_event_classification: false
#   save_metrics: false
#   save_metrics_fp: /home/filip-marcus/results/eneryield_final/interruption_in_seq_event_label_class_dist_interruption3_interruption5_interruption7

data_config:
  save_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/data/processed/eneryield_final
  max_seq_len: 256