defaults:
  - parameters: finetuning
  - _self_

entity: marcus-student-chalmers-personal
project: syntheti0_ft_sweep
program: finetune.py
method: bayes
name: EST_FT_sweep_synthetic_0
metric:
  goal: minimize
  name: task_loss
early_terminate:
  type: hyperband
  min_iter: 1000
# log_every_n_steps: 2

parameters:
  do_overwrite: 
    value: true
  optimization_config:
    num_dataloader_workers:
      value: 5
    max_epochs: 
      value: 1000
    patience:
      value: null
    init_lr:
      max: 1e-1
      min: 1e-7
  task_df_name: 
    value: task_df_synthetic_interruption_in_seq
  load_from_model_dir: 
    value: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_0/
  seed: 
    value: 1
  pretrained_weights_fp: 
    value: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_0/pretrained_weights

  data_config:
    save_dir: 
      value: /home/filip-marcus/ESGPT_new/EventStreamGPT/data/processed/synthetic_0
