defaults:
  - pretrain_config
  - _self_

config:
  TTE_generation_layer_type: log_normal_mixture
  TTE_lognormal_generation_num_components: 13
  attention_dropout: 0.4304595224548104
  categorical_embedding_dim: 67
  categorical_embedding_weight: 0.5295020553028275
  do_full_block_in_dep_graph_attention: false
  do_full_block_in_seq_attention: true
  do_normalize_by_measurement_index: true
  do_split_embeddings: false
  do_use_learnable_sinusoidal_ATE: false
  head_dim: 18
  input_dropout: 0.45134003264588146
  intermediate_size: 128
  num_attention_heads: 10
  num_hidden_layers: 8
  numerical_embedding_dim: 118
  resid_dropout: 0.4777212129911568
  seq_attention_types: global
  seq_window_size: 46
  static_embedding_mode: drop
  static_embedding_weight: 0.9863513359013114
  structured_event_processing_mode: conditionally_independent
  cohort_name: synthetic_0

data_config:
  max_seq_len: 409
  min_seq_len: 13
  save_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/data/processed/synthetic_0
  train_subset_seed: 1
  train_subset_size: FULL

do_final_validation_on_metrics: true
do_overwrite: true
experiment_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT

final_validation_metrics_config:
  do_skip_all_metrics: false
  n_auc_thresholds: 25

pretraining_metrics_config:
  do_skip_all_metrics: false

trainer_config:
  detect_anomaly: false
  log_every_n_steps: 20
wandb_logger_kwargs:  
  do_log_graph: false
  log_model: false
  name: generative_event_stream_transformer
  project: Hyperparameter_sweep_synthetic_0

optimization_config:
  init_lr: 0.0006398098082729676
  end_lr: 8.05022482949952e-06
  end_lr_frac_of_init_lr: 0.012582215410591178
  max_epochs: 100
  batch_size: 106
  validation_batch_size: 32
  lr_frac_warmup_steps: 6.821087018693635e-06
  lr_num_warmup_steps: 0
  max_training_steps: 700
  lr_decay_power: 4.915424972614257
  weight_decay: 0.927050268775883
  patience: 10
  gradient_accumulation: 1
  gradient_clip_val: 1
  num_dataloader_workers: 5

