defaults:
  - finetune_config
  - _self_

do_overwrite: false
seed: 1
load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_mega
task_df_name: task_df_synthetic_interruption_cls
pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_mega/pretrained_weights
data_config:
  save_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/data/processed/synthetic_mega
  min_seq_len: 2
  max_seq_len: 256
optimization_config:
  num_dataloader_workers: 5
  max_epochs: 100
