defaults:
  - finetune_config
  - _self_

do_overwrite: true
seed: 1


# Strategy:  (event label) DONE!
load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield1/
task_df_name: task_df_eneryield_event_label1
pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield1/pretrained_weights
config:
  is_cls_dist: false
  is_event_classification: true
  save_metrics: true
  save_metrics_fp: /home/filip-marcus/results/eneryield1/event_label_baseline
  attention_dropout: 0.37095753535983533
  input_dropout: 0.3265953496759549
  resid_dropout: 0.3792072919318949
  task_specific_params:
    pooling_method: mean


# # Strategy:  (event label) 
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield/
# task_df_name: task_df_eneryield_interruption_in_seq
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield/pretrained_weights
# config:
#   is_cls_dist: true
#   is_event_classification: false
#   save_metrics: true
#   save_metrics_fp: /home/filip-marcus/results/test/test2


# # Strategy:  (event label --> interruption in seq) 
# strategy: true
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield/finetuning/task_df_eneryield_event_label
# task_df_name: task_df_eneryield_interruption_in_seq
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield/finetuning/task_df_eneryield_event_label/finetune_weights
# config:
#   is_cls_dist: false
#   is_event_classification: false

# # Strategy:  (event label --> interruption in seq --> interruptin next week) 
# strategy: true
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield/finetuning/task_df_eneryield_event_label/task_df_eneryield_interruption_in_seq
# task_df_name: task_df_eneryield_interruption_next_week
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield/finetuning/task_df_eneryield_event_label/task_df_eneryield_interruption_in_seq/finetune_weights
# config:
#   is_cls_dist: false
#   is_event_classification: false


data_config:
  save_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/data/processed/eneryield1
  max_seq_len: 256
optimization_config:
  init_lr: 0.06097160660087203
  end_lr: 7.27100151660957e-05
  end_lr_frac_of_init_lr: 0.0011925225399104997
  max_epochs: 23
  batch_size: 45
  validation_batch_size: 32
  lr_frac_warmup_steps: 0.05486192025680797
  lr_num_warmup_steps: 44
  max_training_steps: 800
  lr_decay_power: 3.533808977111257
  weight_decay: 0.0005686424826998055
  patience: null
  gradient_accumulation: 1
  gradient_clip_val: 1
  num_dataloader_workers: 5




    # init_lr: 0.002846394145333227
    # end_lr: 2.3329478071180696e-05
    # end_lr_frac_of_init_lr: 0.008196151650125572
    # max_epochs: 200
    # batch_size: 12
    # validation_batch_size: 32
    # lr_frac_warmup_steps: 3.5555186373837375e-06
    # lr_num_warmup_steps: 0
    # max_training_steps: 2800
    # lr_decay_power: 1.4708137696434
    # weight_decay: 0.00847623042952091
    # patience: 10
    # gradient_accumulation: 1
    # gradient_clip_val: 1
    # num_dataloader_workers: 5