defaults:
  - finetune_config
  - _self_

do_overwrite: true
seed: 1
strategy: true
# Strategy:  (class dist)
load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield2
task_df_name: task_df_eneryield_interruption_3_day2
pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield2/pretrained_weights
config:
  is_cls_dist: false
  is_event_classification: false
  save_metrics: true
  save_metrics_fp: /home/filip-marcus/results/eneryield2/interruption_in_seq_baseline
  attention_dropout: 0.20936669325995003
  input_dropout: 0.4472361690769503
  resid_dropout: 0.4602971575435897
  task_specific_params:
    pooling_method: max

data_config:
  save_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/data/processed/eneryield2
  max_seq_len: 256

optimization_config:
  init_lr: 0.00034353227307836246 # 3.4353e-4
  #0,00001103590125 1.1036e-5
  end_lr: null
  end_lr_frac_of_init_lr: 0.03212522975609648
  max_epochs: 1
  batch_size: 62
  validation_batch_size: 32
  lr_frac_warmup_steps: 0.00010576875220433304
  lr_num_warmup_steps: 0
  max_training_steps: 600
  lr_decay_power: 2.9713167898962407
  weight_decay: 0.01736952156892551 # 1.7370e-2
  patience: 15
  gradient_accumulation: 1
  gradient_clip_val: 1
  num_dataloader_workers: 5