defaults:
  - finetune_config
  - _self_

do_overwrite: true
seed: 1

# # Strategy:  (interruption 5 day)
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield1/
# task_df_name: task_df_eneryield_interruption_5_day1
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield1/pretrained_weights
# config:
#   is_cls_dist: false
#   is_event_classification: false
#   save_metrics: true
#   is_interruption_forecast: true
#   save_metrics_fp: /home/filip-marcus/results/eneryield1/interruption_5_day_baseline
#   attention_dropout: 0.1837802708386887
#   input_dropout: 0.292396445992673
#   resid_dropout: 0.16731080945583016
#   task_specific_params:
#     pooling_method: last



# # Strategy:  (class dist --> event label --> interruption in sequence --> interruption 3 day --> interruption 5 day) 
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield1/finetuning/task_df_eneryield_class_dist1/finetuning/task_df_eneryield_event_label1/finetuning/task_df_eneryield_interruption_in_seq1/finetuning/task_df_eneryield_interruption_3_day1
# task_df_name: task_df_eneryield_interruption_5_day1
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield1/finetuning/task_df_eneryield_class_dist1/finetuning/task_df_eneryield_event_label1/finetuning/task_df_eneryield_interruption_in_seq1/finetuning/task_df_eneryield_interruption_3_day1/finetune_weights
# config:
#   is_cls_dist: false
#   is_event_classification: false
#   save_metrics: true
#   save_metrics_fp: /home/filip-marcus/results/eneryield1/class_dist_event_label_interruption_in_seq_interruption3_interruption_5_day
#   is_pretrain: false
#   is_interruption_forecast: true
#   attention_dropout: 0.1837802708386887
#   input_dropout: 0.292396445992673
#   resid_dropout: 0.16731080945583016
#   task_specific_params:
#     pooling_method: last


# # Strategy:  (class dist --> interruption in sequence --> event label --> interruption 3 day --> interruption 5 day) 
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield1/finetuning/task_df_eneryield_class_dist1/finetuning/task_df_eneryield_interruption_in_seq1/finetuning/task_df_eneryield_event_label1/finetuning/task_df_eneryield_interruption_3_day1
# task_df_name: task_df_eneryield_interruption_5_day1
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield1/finetuning/task_df_eneryield_class_dist1/finetuning/task_df_eneryield_interruption_in_seq1/finetuning/task_df_eneryield_event_label1/finetuning/task_df_eneryield_interruption_3_day1/finetune_weights
# config:
#   is_cls_dist: false
#   is_event_classification: false
#   save_metrics: true
#   save_metrics_fp: /home/filip-marcus/results/eneryield1/class_dist_interruption_in_seq_event_label_interruption3_interruption5
#   is_pretrain: false
#   is_interruption_forecast: true
#   attention_dropout: 0.18461243586389464
#   input_dropout: 0.2676812758737818
#   resid_dropout: 0.03790906346913303
#   task_specific_params:
#     pooling_method: max 


# # Strategy:  (event label --> class dist --> interruption in sequence --> interruption 3 day --> interruption 5 day) 
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield1/finetuning/task_df_eneryield_event_label1/finetuning/task_df_eneryield_class_dist1/finetuning/task_df_eneryield_interruption_in_seq1/finetuning/task_df_eneryield_interruption_3_day1
# task_df_name: task_df_eneryield_interruption_5_day1
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield1/finetuning/task_df_eneryield_event_label1/finetuning/task_df_eneryield_class_dist1/finetuning/task_df_eneryield_interruption_in_seq1/finetuning/task_df_eneryield_interruption_3_day1/finetune_weights
# config:
#   is_cls_dist: false
#   is_event_classification: false
#   save_metrics: true
#   save_metrics_fp: /home/filip-marcus/results/eneryield1/event_label_class_dist_interruption_in_seq_interruption3_interruption5
#   is_pretrain: false
#   is_interruption_forecast: true
#   attention_dropout: 0.18461243586389464
#   input_dropout: 0.2676812758737818
#   resid_dropout: 0.03790906346913303
#   task_specific_params:
#     pooling_method: max 

# # Strategy:  (event label --> interruption in sequence --> class dist --> interruption 3 day --> interruption 5 day) 
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield1/finetuning/task_df_eneryield_event_label1/finetuning/task_df_eneryield_interruption_in_seq1/finetuning/task_df_eneryield_class_dist1/finetuning/task_df_eneryield_interruption_3_day1
# task_df_name: task_df_eneryield_interruption_5_day1
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield1/finetuning/task_df_eneryield_event_label1/finetuning/task_df_eneryield_interruption_in_seq1/finetuning/task_df_eneryield_class_dist1/finetuning/task_df_eneryield_interruption_3_day1/finetune_weights
# config:
#   is_cls_dist: false
#   is_event_classification: false
#   save_metrics: true
#   save_metrics_fp: /home/filip-marcus/results/eneryield1/event_label_interruption_in_seq_class_dist_interruption3_interruption5
#   is_pretrain: false
#   is_interruption_forecast: true
#   attention_dropout: 0.18461243586389464
#   input_dropout: 0.2676812758737818
#   resid_dropout: 0.03790906346913303
#   task_specific_params:
#     pooling_method: max 


# # Strategy:  (interruption in seq --> class dist --> event label --> interruption 3 day --> interruption 5 day) 
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield1/finetuning/task_df_eneryield_interruption_in_seq1/finetuning/task_df_eneryield_class_dist1/finetuning/task_df_eneryield_event_label1/finetuning/task_df_eneryield_interruption_3_day1
# task_df_name: task_df_eneryield_interruption_5_day1
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield1/finetuning/task_df_eneryield_interruption_in_seq1/finetuning/task_df_eneryield_class_dist1/finetuning/task_df_eneryield_event_label1/finetuning/task_df_eneryield_interruption_3_day1/finetune_weights
# config:
#   is_cls_dist: false
#   is_event_classification: false
#   save_metrics: true
#   save_metrics_fp: /home/filip-marcus/results/eneryield1/interruption_in_seq_class_dist_event_label_interruption3_interruption5
#   is_pretrain: false
#   is_interruption_forecast: true
#   attention_dropout: 0.18461243586389464
#   input_dropout: 0.2676812758737818
#   resid_dropout: 0.03790906346913303
#   task_specific_params:
#     pooling_method: max 

# Strategy:  (interruption in seq --> event label --> class dist --> interruption 3 day --> interruption 5 day) 
load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield1/finetuning/task_df_eneryield_interruption_in_seq1/finetuning/task_df_eneryield_event_label1/finetuning/task_df_eneryield_class_dist1/finetuning/task_df_eneryield_interruption_3_day1
task_df_name: task_df_eneryield_interruption_5_day1
pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield1/finetuning/task_df_eneryield_interruption_in_seq1/finetuning/task_df_eneryield_event_label1/finetuning/task_df_eneryield_class_dist1/finetuning/task_df_eneryield_interruption_3_day1/finetune_weights
config:
  is_cls_dist: false
  is_event_classification: false
  save_metrics: true
  save_metrics_fp: /home/filip-marcus/results/eneryield1/interruption_in_seq_event_label_class_dist_interruption3_interruption5
  is_pretrain: false
  is_interruption_forecast: true
  attention_dropout: 0.18461243586389464
  input_dropout: 0.2676812758737818
  resid_dropout: 0.03790906346913303
  task_specific_params:
    pooling_method: max 

data_config:
  save_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/data/processed/eneryield1
  max_seq_len: 256

optimization_config:
  init_lr: 0.07858665611204341
  end_lr: 0.011012541687150474
  end_lr_frac_of_init_lr: 0.1401324630920745
  max_epochs: 30
  batch_size: 55
  validation_batch_size: 32
  lr_frac_warmup_steps: 5.625787010852111e-06
  lr_num_warmup_steps: 0
  max_training_steps: 1200
  lr_decay_power: 1.9143918962751791
  weight_decay: 0.3655512683995653
  patience: null
  gradient_accumulation: 1
  gradient_clip_val: 1
  num_dataloader_workers: 5