defaults:
  - finetune_config
  - _self_

do_overwrite: true
seed: 1

# # Strategy: 
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield1/
# task_df_name: task_df_eneryield_interruption_in_seq1
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield1/pretrained_weights
# config:
#   is_cls_dist: false
#   is_event_classification: false
#   save_metrics: true
#   is_interruption_forecast: false
#   save_metrics_fp: /home/filip-marcus/results/eneryield1/interruption_in_seq_baseline
#   attention_dropout: 0.38949734643478434
#   input_dropout: 0.3716604394858833
#   resid_dropout: 0.3539164418342992
#   task_specific_params:
#     pooling_method: cls


# # Strategy:  (class dist --> event label --> interruption in sequence) 
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield1/finetuning/task_df_eneryield_class_dist1/finetuning/task_df_eneryield_event_label1
# task_df_name: task_df_eneryield_interruption_in_seq1
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield1/finetuning/task_df_eneryield_class_dist1/finetuning/task_df_eneryield_event_label1/finetune_weights
# config:
#   is_cls_dist: false
#   is_event_classification: false
#   save_metrics: true
#   save_metrics_fp: /home/filip-marcus/results/eneryield1/class_dist_event_label_interruption_in_seq
#   is_pretrain: false
#   attention_dropout: 0.38949734643478434
#   input_dropout: 0.3716604394858833
#   resid_dropout: 0.3539164418342992
#   task_specific_params:
#     pooling_method: cls


# # Strategy:  (class dist --> interruption in sequence) 
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield1/finetuning/task_df_eneryield_class_dist1
# task_df_name: task_df_eneryield_interruption_in_seq1
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield1/finetuning/task_df_eneryield_class_dist1/finetune_weights
# config:
#   is_cls_dist: false
#   is_event_classification: false
#   save_metrics: true
#   save_metrics_fp: /home/filip-marcus/results/eneryield1/class_dist_interruption_in_seq
#   is_pretrain: false
#   attention_dropout: 0.38949734643478434
#   input_dropout: 0.3716604394858833
#   resid_dropout: 0.3539164418342992
#   task_specific_params:
#     pooling_method: cls


# # Strategy:  (event label --> class dist --> interruption in sequence) 
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield1/finetuning/task_df_eneryield_event_label1/finetuning/task_df_eneryield_class_dist1
# task_df_name: task_df_eneryield_interruption_in_seq1
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield1/finetuning/task_df_eneryield_event_label1/finetuning/task_df_eneryield_class_dist1/finetune_weights
# config:
#   is_cls_dist: false
#   is_event_classification: false
#   save_metrics: true
#   save_metrics_fp: /home/filip-marcus/results/eneryield1/event_label_class_dist_interruption_in_seq
#   is_pretrain: false
#   attention_dropout: 0.38949734643478434
#   input_dropout: 0.3716604394858833
#   resid_dropout: 0.3539164418342992
#   task_specific_params:
#     pooling_method: cls

# Strategy:  (event label --> interruption in sequence) 
load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield1/finetuning/task_df_eneryield_event_label1
task_df_name: task_df_eneryield_interruption_in_seq1
pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield1/finetuning/task_df_eneryield_event_label1/finetune_weights
config:
  is_cls_dist: false
  is_event_classification: false
  save_metrics: true
  save_metrics_fp: /home/filip-marcus/results/eneryield1/event_label_interruption_in_seq
  is_pretrain: false
  attention_dropout: 0.38949734643478434
  input_dropout: 0.3716604394858833
  resid_dropout: 0.3539164418342992
  task_specific_params:
    pooling_method: cls


data_config:
  save_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/data/processed/eneryield1
  max_seq_len: 256
optimization_config:
  init_lr: 0.007594946892309613
  end_lr: 1.3419771710805059e-05
  end_lr_frac_of_init_lr: 0.0017669342394472129
  max_epochs: 14
  batch_size: 13
  validation_batch_size: 32
  lr_frac_warmup_steps: 0.0020190714968606523
  lr_num_warmup_steps: 10
  max_training_steps: 4800
  lr_decay_power: 2.490314894564632
  weight_decay: 0.15586918542735004
  patience: null
  gradient_accumulation: 1
  gradient_clip_val: 1
  num_dataloader_workers: 5