defaults:
  - finetune_config
  - _self_

do_overwrite: true
seed: 1

# Strategy:  (class dist)

load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield2/
task_df_name: task_df_eneryield_class_dist2
pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield2/pretrained_weights
config:
  is_cls_dist: true
  is_event_classification: false
  save_metrics: true
  save_metrics_fp: /home/filip-marcus/results/eneryield2/class_dist_baseline
  is_pretrain: false
  attention_dropout: 0.06142001777754119
  input_dropout: 0.38867480143304617
  resid_dropout: 0.09425282831457392
  task_specific_params:
    pooling_method: mean




data_config:
  save_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/data/processed/eneryield2
  max_seq_len: 256
optimization_config:
  init_lr: 0.0012204875480758986
  end_lr: 1.3806787904406103e-05
  end_lr_frac_of_init_lr: 0.01131251844901862
  max_epochs: 50
  batch_size: 31
  validation_batch_size: 32
  lr_frac_warmup_steps: 2.114249365648493e-05
  lr_num_warmup_steps: 0
  max_training_steps: 6400
  lr_decay_power: 1.880987788652173
  weight_decay: 0.0026591132503731483
  patience: 8
  gradient_accumulation: 1
  gradient_clip_val: 1
  num_dataloader_workers: 5