defaults:
  - finetune_config
  - _self_

do_overwrite: true
seed: 1
is_inference: true # Flag to indicate that this is an inference run
task_type: class_dist # Task type for the inference run - used to use the appropirate evaluation metrics

data_config:
  save_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/data/processed/giga_mind
  max_seq_len: 256

# Strategy:  (class dist)
load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/giga_mind/finetuning/task_df_giga_mind_class_dist
task_df_name: task_df_giga_mind_class_dist
pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/giga_mind/finetuning/task_df_giga_mind_class_dist/finetune_weights

config:
  is_cls_dist: true
  is_event_classification: false
  save_metrics: false
  save_metrics_fp: /home/filip-marcus/results/giga_mind/interruption_class_dist_baseline

