defaults:
  - finetune_config
  - _self_

do_overwrite: true
seed: 1

# Strategy:  (class dist)
load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/giga_mind/
task_df_name: task_df_eneryield_interruption_1_day1
pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/giga_mind/pretrained_weights

config:
  is_cls_dist: false
  is_event_classification: false
  save_metrics: false
  is_interruption_forecast: true
  save_metrics_fp: /home/filip-marcus/results/giga_mind/interruption_in_seq_baseline
  attention_dropout: 0.4273428080552211
  input_dropout: 0.19168076431935263
  resid_dropout: 0.09981219410925546
  task_specific_params:
    pooling_method: last

data_config:
  save_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/data/processed/giga_mind
  max_seq_len: 256
  seq_padding_side: left

optimization_config:
  init_lr: 0.0029992873733337626
  end_lr: 1.1747943049022066e-05
  end_lr_frac_of_init_lr: 0.003916911448189779
  max_epochs: 50
  batch_size: 23
  validation_batch_size: 32
  lr_frac_warmup_steps: 5.91126662482909e-06
  lr_num_warmup_steps: 0
  max_training_steps: 1600
  lr_decay_power: 3.8784740419116615
  weight_decay: 0.2919392016956252
  patience: null
  gradient_accumulation: 1
  gradient_clip_val: 1
  num_dataloader_workers: 5