defaults:
  - finetune_config
  - _self_

do_overwrite: true
seed: 1

# Strategy:  (interruption 5 day)
load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/giga_mind/
task_df_name: task_df_giga_mind_interruption_5_day
pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/giga_mind/pretrained_weights
config:
  is_cls_dist: false
  is_event_classification: false
  save_metrics: true
  is_interruption_forecast: true
  save_metrics_fp: /home/filip-marcus/results/giga_mind/interruption_5_day_baseline
  attention_dropout: 0.2499271824938041
  input_dropout: 0.029501033609348803
  resid_dropout: 0.36248428708797753
  task_specific_params:
    pooling_method: mean



# # Strategy:  (class dist --> event label --> interruption in sequence --> interruption 3 day --> interruption 5 day) 
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/giga_mind/finetuning/task_df_giga_mind_class_dist1/finetuning/task_df_giga_mind_event_label1/finetuning/task_df_giga_mind_interruption_in_seq1/finetuning/task_df_giga_mind_interruption_3_day1
# task_df_name: task_df_giga_mind_interruption_5_day1
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/giga_mind/finetuning/task_df_giga_mind_class_dist1/finetuning/task_df_giga_mind_event_label1/finetuning/task_df_giga_mind_interruption_in_seq1/finetuning/task_df_giga_mind_interruption_3_day1/finetune_weights
# config:
#   is_cls_dist: false
#   is_event_classification: false
#   save_metrics: true
#   save_metrics_fp: /home/filip-marcus/results/giga_mind/class_dist_event_label_interruption_in_seq_interruption3_interruption_5_day
#   is_pretrain: false
#   attention_dropout: 0.18461243586389464
#   input_dropout: 0.2676812758737818
#   resid_dropout: 0.03790906346913303
#   task_specific_params:
#     pooling_method: max


# # Strategy:  (class dist --> interruption in sequence --> event label --> interruption 3 day --> interruption 5 day) 
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/giga_mind/finetuning/task_df_giga_mind_class_dist1/finetuning/task_df_giga_mind_interruption_in_seq1/finetuning/task_df_giga_mind_event_label1/finetuning/task_df_giga_mind_interruption_3_day1
# task_df_name: task_df_giga_mind_interruption_5_day1
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/giga_mind/finetuning/task_df_giga_mind_class_dist1/finetuning/task_df_giga_mind_interruption_in_seq1/finetuning/task_df_giga_mind_event_label1/finetuning/task_df_giga_mind_interruption_3_day1/finetune_weights
# config:
#   is_cls_dist: false
#   is_event_classification: false
#   save_metrics: true
#   save_metrics_fp: /home/filip-marcus/results/giga_mind/class_dist_interruption_in_seq_event_label_interruption3_interruption5
#   is_pretrain: false
#   attention_dropout: 0.18461243586389464
#   input_dropout: 0.2676812758737818
#   resid_dropout: 0.03790906346913303
#   task_specific_params:
#     pooling_method: max 


# # Strategy:  (event label --> class dist --> interruption in sequence --> interruption 3 day --> interruption 5 day) 
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/giga_mind/finetuning/task_df_giga_mind_event_label1/finetuning/task_df_giga_mind_class_dist1/finetuning/task_df_giga_mind_interruption_in_seq1/finetuning/task_df_giga_mind_interruption_3_day1
# task_df_name: task_df_giga_mind_interruption_5_day1
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/giga_mind/finetuning/task_df_giga_mind_event_label1/finetuning/task_df_giga_mind_class_dist1/finetuning/task_df_giga_mind_interruption_in_seq1/finetuning/task_df_giga_mind_interruption_3_day1/finetune_weights
# config:
#   is_cls_dist: false
#   is_event_classification: false
#   save_metrics: true
#   save_metrics_fp: /home/filip-marcus/results/giga_mind/event_label_class_dist_interruption_in_seq_interruption3_interruption5
#   is_pretrain: false
#   attention_dropout: 0.18461243586389464
#   input_dropout: 0.2676812758737818
#   resid_dropout: 0.03790906346913303
#   task_specific_params:
#     pooling_method: max 

# # Strategy:  (event label --> interruption in sequence --> class dist --> interruption 3 day --> interruption 5 day) 
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/giga_mind/finetuning/task_df_giga_mind_event_label1/finetuning/task_df_giga_mind_interruption_in_seq1/finetuning/task_df_giga_mind_class_dist1/finetuning/task_df_giga_mind_interruption_3_day1
# task_df_name: task_df_giga_mind_interruption_5_day1
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/giga_mind/finetuning/task_df_giga_mind_event_label1/finetuning/task_df_giga_mind_interruption_in_seq1/finetuning/task_df_giga_mind_class_dist1/finetuning/task_df_giga_mind_interruption_3_day1/finetune_weights
# config:
#   is_cls_dist: false
#   is_event_classification: false
#   save_metrics: true
#   save_metrics_fp: /home/filip-marcus/results/giga_mind/event_label_interruption_in_seq_class_dist_interruption3_interruption5
#   is_pretrain: false
#   attention_dropout: 0.18461243586389464
#   input_dropout: 0.2676812758737818
#   resid_dropout: 0.03790906346913303
#   task_specific_params:
#     pooling_method: max 


# # Strategy:  (interruption in seq --> class dist --> event label --> interruption 3 day --> interruption 5 day) 
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/giga_mind/finetuning/task_df_giga_mind_interruption_in_seq1/finetuning/task_df_giga_mind_class_dist1/finetuning/task_df_giga_mind_event_label1/finetuning/task_df_giga_mind_interruption_3_day1
# task_df_name: task_df_giga_mind_interruption_5_day1
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/giga_mind/finetuning/task_df_giga_mind_interruption_in_seq1/finetuning/task_df_giga_mind_class_dist1/finetuning/task_df_giga_mind_event_label1/finetuning/task_df_giga_mind_interruption_3_day1/finetune_weights
# config:
#   is_cls_dist: false
#   is_event_classification: false
#   save_metrics: true
#   save_metrics_fp: /home/filip-marcus/results/giga_mind/interruption_in_seq_class_dist_event_label_interruption3_interruption5
#   is_pretrain: false
#   attention_dropout: 0.18461243586389464
#   input_dropout: 0.2676812758737818
#   resid_dropout: 0.03790906346913303
#   task_specific_params:
#     pooling_method: max 

# # Strategy:  (interruption in seq --> event label --> class dist --> interruption 3 day --> interruption 5 day) 
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/giga_mind/finetuning/task_df_giga_mind_interruption_in_seq1/finetuning/task_df_giga_mind_event_label1/finetuning/task_df_giga_mind_class_dist1/finetuning/task_df_giga_mind_interruption_3_day1
# task_df_name: task_df_giga_mind_interruption_5_day1
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/giga_mind/finetuning/task_df_giga_mind_interruption_in_seq1/finetuning/task_df_giga_mind_event_label1/finetuning/task_df_giga_mind_class_dist1/finetuning/task_df_giga_mind_interruption_3_day1/finetune_weights
# config:
#   is_cls_dist: false
#   is_event_classification: false
#   save_metrics: true
#   save_metrics_fp: /home/filip-marcus/results/giga_mind/interruption_in_seq_event_label_class_dist_interruption3_interruption5
#   is_pretrain: false
#   attention_dropout: 0.18461243586389464
#   input_dropout: 0.2676812758737818
#   resid_dropout: 0.03790906346913303
#   task_specific_params:
#     pooling_method: max 

data_config:
  save_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/data/processed/giga_mind
  seq_padding_side: left
  max_seq_len: 256

optimization_config:
  init_lr: 0.10565814070148127
  end_lr: 0.0036406940613845857
  end_lr_frac_of_init_lr: 0.03445729819977369
  max_epochs: 200
  batch_size: 60
  validation_batch_size: 32
  lr_frac_warmup_steps: 0.03552388818169591
  lr_num_warmup_steps: 128
  max_training_steps: 3600
  lr_decay_power: 3.932916324209595
  weight_decay: 0.2282657157930197
  patience: 15
  gradient_accumulation: 1
  gradient_clip_val: 1
  num_dataloader_workers: 5