defaults:
  - finetune_config
  - _self_

do_overwrite: true
seed: 1

# Strategy:  (class dist)
load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/giga_mind/
task_df_name: task_df_giga_mind_interruption_3_day
pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/giga_mind/pretrained_weights
config:
  is_cls_dist: false
  is_event_classification: false
  save_metrics: false
  save_metrics_fp: /home/filip-marcus/results/giga_mind/interruption_3_day_baseline
  attention_dropout: 0.09153289545361865
  input_dropout: 0.3958239248386486
  resid_dropout: 0.12879814545385304
  is_interruption_forecast: true
  task_specific_params:
    pooling_method: max



# # Strategy:  (class dist --> event label --> interruption in sequence --> interruption 3 day) 
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/giga_mind/finetuning/task_df_giga_mind_class_dist1/finetuning/task_df_giga_mind_event_label1/finetuning/task_df_giga_mind_interruption_in_seq1
# task_df_name: task_df_giga_mind_interruption_3_day1
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/giga_mind/finetuning/task_df_giga_mind_class_dist1/finetuning/task_df_giga_mind_event_label1/finetuning/task_df_giga_mind_interruption_in_seq1/finetune_weights
# config:
#   is_cls_dist: false
#   is_event_classification: false
#   save_metrics: true
#   save_metrics_fp: /home/filip-marcus/results/giga_mind/class_dist_event_label_interruption_in_seq_interruption3
#   is_pretrain: false
#   attention_dropout: 0.016545291643366045
#   input_dropout: 0.28235305317016207
#   resid_dropout: 0.35993321740987977
#   task_specific_params:
#     pooling_method: mean



# # Strategy:  (class dist --> interruption in sequence --> event label --> interruption 3 day) 
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/giga_mind/finetuning/task_df_giga_mind_class_dist1/finetuning/task_df_giga_mind_interruption_in_seq1/finetuning/task_df_giga_mind_event_label1
# task_df_name: task_df_giga_mind_interruption_3_day1
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/giga_mind/finetuning/task_df_giga_mind_class_dist1/finetuning/task_df_giga_mind_interruption_in_seq1/finetuning/task_df_giga_mind_event_label1/finetune_weights
# config:
#   is_cls_dist: false
#   is_event_classification: false
#   save_metrics: true
#   save_metrics_fp: /home/filip-marcus/results/giga_mind/class_dist_interruption_in_seq_event_label_interruption3
#   is_pretrain: false
#   attention_dropout: 0.016545291643366045
#   input_dropout: 0.28235305317016207
#   resid_dropout: 0.35993321740987977
#   task_specific_params:
#     pooling_method: mean

# # Strategy:  (event label --> class dist --> interruption in sequence --> interruption 3 day) 
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/giga_mind/finetuning/task_df_giga_mind_event_label1/finetuning/task_df_giga_mind_class_dist1/finetuning/task_df_giga_mind_interruption_in_seq1
# task_df_name: task_df_giga_mind_interruption_3_day1
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/giga_mind/finetuning/task_df_giga_mind_event_label1/finetuning/task_df_giga_mind_class_dist1/finetuning/task_df_giga_mind_interruption_in_seq1/finetune_weights
# config:
#   is_cls_dist: false
#   is_event_classification: false
#   save_metrics: true
#   save_metrics_fp: /home/filip-marcus/results/giga_mind/event_label_class_dist_interruption_in_seq_interruption3
#   is_pretrain: false
#   attention_dropout: 0.016545291643366045
#   input_dropout: 0.28235305317016207
#   resid_dropout: 0.35993321740987977
#   task_specific_params:
#     pooling_method: mean

# # Strategy:  (event label --> interruption in sequence --> class dist --> interruption 3 day) 
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/giga_mind/finetuning/task_df_giga_mind_event_label1/finetuning/task_df_giga_mind_interruption_in_seq1/finetuning/task_df_giga_mind_class_dist1
# task_df_name: task_df_giga_mind_interruption_3_day1
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/giga_mind/finetuning/task_df_giga_mind_event_label1/finetuning/task_df_giga_mind_interruption_in_seq1/finetuning/task_df_giga_mind_class_dist1/finetune_weights
# config:
#   is_cls_dist: false
#   is_event_classification: false
#   save_metrics: true
#   save_metrics_fp: /home/filip-marcus/results/giga_mind/event_label_interruption_in_seq_class_dist_interruption3
#   is_pretrain: false
#   attention_dropout: 0.016545291643366045
#   input_dropout: 0.28235305317016207
#   resid_dropout: 0.35993321740987977
#   task_specific_params:
#     pooling_method: mean


# # Strategy:  (interruption in seq --> class dist --> event label) 
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/giga_mind/finetuning/task_df_giga_mind_interruption_in_seq1/finetuning/task_df_giga_mind_class_dist1/finetuning/task_df_giga_mind_event_label1
# task_df_name: task_df_giga_mind_interruption_3_day1
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/giga_mind/finetuning/task_df_giga_mind_interruption_in_seq1/finetuning/task_df_giga_mind_class_dist1/finetuning/task_df_giga_mind_event_label1/finetune_weights
# config:
#   is_cls_dist: false
#   is_event_classification: false
#   save_metrics: true
#   save_metrics_fp: /home/filip-marcus/results/giga_mind/interruption_in_seq_class_dist_event_label_interruption3
#   is_pretrain: false
#   attention_dropout: 0.016545291643366045
#   input_dropout: 0.28235305317016207
#   resid_dropout: 0.35993321740987977
#   task_specific_params:
#     pooling_method: mean

# # Strategy:  (interruption in seq --> event label --> class dist --> interruption 3 day) 
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/giga_mind/finetuning/task_df_giga_mind_interruption_in_seq1/finetuning/task_df_giga_mind_event_label1/finetuning/task_df_giga_mind_class_dist1
# task_df_name: task_df_giga_mind_interruption_3_day1
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/giga_mind/finetuning/task_df_giga_mind_interruption_in_seq1/finetuning/task_df_giga_mind_event_label1/finetuning/task_df_giga_mind_class_dist1/finetune_weights
# config:
#   is_cls_dist: false
#   is_event_classification: false
#   save_metrics: true
#   save_metrics_fp: /home/filip-marcus/results/giga_mind/interruption_in_seq_event_label_class_dist_interruption3
#   is_pretrain: false
#   attention_dropout: 0.016545291643366045
#   input_dropout: 0.28235305317016207
#   resid_dropout: 0.35993321740987977
#   task_specific_params:
#     pooling_method: mean

data_config:
  save_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/data/processed/giga_mind
  max_seq_len: 256
  seq_padding_side: left

optimization_config:
  init_lr: 0.0003337824389008253
  end_lr: 6.486227076464023e-05
  end_lr_frac_of_init_lr: 0.19432499498247224
  max_epochs: 200
  batch_size: 9
  validation_batch_size: 32
  lr_frac_warmup_steps: 0.00024225416397755957
  lr_num_warmup_steps: 6
  max_training_steps: 23800
  lr_decay_power: 3.927846507579557
  weight_decay: 0.4799349316041168
  patience: 15
  gradient_accumulation: 1
  gradient_clip_val: 1
  num_dataloader_workers: 5