defaults:
  - finetune_config
  - _self_

do_overwrite: true
seed: 1

# # Strategy:  (class dist)
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/giga_mind/
# task_df_name: task_df_giga_mind_class_dist
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/giga_mind/pretrained_weights
# config:
#   is_cls_dist: true
#   is_event_classification: false
#   save_metrics: true
#   save_metrics_fp: /home/filip-marcus/results/giga_mind/class_dist_baseline_new
#   is_pretrain: false
#   attention_dropout: 0.35479209014564606
#   input_dropout: 0.16459312983622948
#   resid_dropout: 0.2271510672939574
#   task_specific_params:
#     pooling_method: max


# Strategy:  (event label --> class dist) 
load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/giga_mind/finetuning/task_df_giga_mind_event_label
task_df_name: task_df_giga_mind_class_dist
pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/giga_mind/finetuning/task_df_giga_mind_event_label/finetune_weights
config:
  is_cls_dist: true
  is_event_classification: false
  save_metrics: true
  save_metrics_fp: /home/filip-marcus/results/giga_mind/event_label_class_dist
  is_pretrain: false
  attention_dropout: 0.35479209014564606
  input_dropout: 0.16459312983622948
  resid_dropout: 0.2271510672939574
  task_specific_params:
    pooling_method: max



# # Strategy:  (event label --> interruption in sequence --> class dist) 
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/giga_mind/finetuning/task_df_giga_mind_event_label/finetuning/task_df_giga_mind_interruption_in_seq
# task_df_name: task_df_giga_mind_class_dist
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/giga_mind/finetuning/task_df_giga_mind_event_label/finetuning/task_df_giga_mind_interruption_in_seq/finetune_weights
# config:
#   is_cls_dist: true
#   is_event_classification: false
#   save_metrics: true
#   save_metrics_fp: /home/filip-marcus/results/giga_mind/event_label_interruption_in_seq_class_dist
#   is_pretrain: false
#   attention_dropout: 0.35479209014564606
#   input_dropout: 0.16459312983622948
#   resid_dropout: 0.2271510672939574
#   task_specific_params:
#     pooling_method: max


# # Strategy:  (interruption in seq --> class dist) 
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/giga_mind/finetuning/task_df_giga_mind_interruption_in_seq
# task_df_name: task_df_giga_mind_class_dist
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/giga_mind/finetuning/task_df_giga_mind_interruption_in_seq/finetune_weights
# config:
#   is_cls_dist: true
#   is_event_classification: false
#   save_metrics: true
#   save_metrics_fp: /home/filip-marcus/results/giga_mind/interruption_in_seq_class_dist
#   is_pretrain: false
#   attention_dropout: 0.35479209014564606
#   input_dropout: 0.16459312983622948
#   resid_dropout: 0.2271510672939574
#   task_specific_params:
#     pooling_method: max

# # Strategy:  (interruption in seq --> event label --> class dist) 
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/giga_mind/finetuning/task_df_giga_mind_interruption_in_seq/finetuning/task_df_giga_mind_event_label
# task_df_name: task_df_giga_mind_class_dist
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/giga_mind/finetuning/task_df_giga_mind_interruption_in_seq/finetuning/task_df_giga_mind_event_label/finetune_weights
# config:
#   is_cls_dist: true
#   is_event_classification: false
#   save_metrics: true
#   save_metrics_fp: /home/filip-marcus/results/giga_mind/interruption_in_seq_event_label_class_dist
#   is_pretrain: false
#   attention_dropout: 0.35479209014564606
#   input_dropout: 0.16459312983622948
#   resid_dropout: 0.2271510672939574
#   task_specific_params:
#     pooling_method: max


data_config:
  save_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/data/processed/giga_mind
  seq_padding_side: left
  max_seq_len: 256
optimization_config:
  init_lr: 0.0028719657745205633
  end_lr: 0.000119880530359456
  end_lr_frac_of_init_lr: 0.04174162917365144
  max_epochs: 46
  batch_size: 49
  validation_batch_size: 32
  lr_frac_warmup_steps: 1.3688732989551112e-05
  lr_num_warmup_steps: 0
  max_training_steps: 4400
  lr_decay_power: 2.0049656461185092
  weight_decay: 0.00747299931496944
  patience: null
  gradient_accumulation: 1
  gradient_clip_val: 1
  num_dataloader_workers: 5
