defaults:
  - finetune_config
  - _self_

do_overwrite: true
seed: 1

# Strategy:  (class dist)
load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/giga_mind_final/
task_df_name: task_df_giga_mind_interruption_3_day
pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/giga_mind_final/pretrained_weights
config:
  is_cls_dist: false
  is_event_classification: false
  save_metrics: true
  save_metrics_fp: /home/filip-marcus/results/giga_mind_final/interruption_3_day_baseline_new
  attention_dropout: 0.09153289545361865
  input_dropout: 0.3958239248386486
  resid_dropout: 0.12879814545385304
  is_interruption_forecast: true
  task_specific_params:
    pooling_method: max



# # Strategy:  (class dist --> event label --> interruption in sequence --> interruption 3 day) 
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/giga_mind/finetuning/task_df_giga_mind_class_dist/finetuning/task_df_giga_mind_event_label/finetuning/task_df_giga_mind_interruption_in_seq
# task_df_name: task_df_giga_mind_interruption_3_day
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/giga_mind/finetuning/task_df_giga_mind_class_dist/finetuning/task_df_giga_mind_event_label/finetuning/task_df_giga_mind_interruption_in_seq/finetune_weights
# config:
#   is_cls_dist: false
#   is_event_classification: false
#   save_metrics: true
#   save_metrics_fp: /home/filip-marcus/results/giga_mind/class_dist_event_label_interruption_in_seq_interruption3
#   is_pretrain: false
#   attention_dropout: 0.09153289545361865
#   input_dropout: 0.3958239248386486
#   resid_dropout: 0.12879814545385304
#   is_interruption_forecast: true
#   task_specific_params:
#     pooling_method: max


  



# # Strategy:  (class dist --> interruption in sequence --> event label --> interruption 3 day) 
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/giga_mind/finetuning/task_df_giga_mind_class_dist/finetuning/task_df_giga_mind_interruption_in_seq/finetuning/task_df_giga_mind_event_label
# task_df_name: task_df_giga_mind_interruption_3_day
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/giga_mind/finetuning/task_df_giga_mind_class_dist/finetuning/task_df_giga_mind_interruption_in_seq/finetuning/task_df_giga_mind_event_label/finetune_weights
# config:
#   is_cls_dist: false
#   is_event_classification: false
#   save_metrics: true
#   save_metrics_fp: /home/filip-marcus/results/giga_mind/class_dist_interruption_in_seq_event_label_interruption3
#   is_pretrain: false
#   attention_dropout: 0.09153289545361865
#   input_dropout: 0.3958239248386486
#   resid_dropout: 0.12879814545385304
#   is_interruption_forecast: true
#   task_specific_params:
#     pooling_method: max

# # Strategy:  (event label --> class dist --> interruption in sequence --> interruption 3 day) 
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/giga_mind/finetuning/task_df_giga_mind_event_label/finetuning/task_df_giga_mind_class_dist/finetuning/task_df_giga_mind_interruption_in_seq
# task_df_name: task_df_giga_mind_interruption_3_day
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/giga_mind/finetuning/task_df_giga_mind_event_label/finetuning/task_df_giga_mind_class_dist/finetuning/task_df_giga_mind_interruption_in_seq/finetune_weights
# config:
#   is_cls_dist: false
#   is_event_classification: false
#   save_metrics: true
#   save_metrics_fp: /home/filip-marcus/results/giga_mind/event_label_class_dist_interruption_in_seq_interruption3
#   is_pretrain: false
#   attention_dropout: 0.09153289545361865
#   input_dropout: 0.3958239248386486
#   resid_dropout: 0.12879814545385304
#   is_interruption_forecast: true
#   task_specific_params:
#     pooling_method: max

# # Strategy:  (event label --> interruption in sequence --> class dist --> interruption 3 day) 
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/giga_mind/finetuning/task_df_giga_mind_event_label/finetuning/task_df_giga_mind_interruption_in_seq/finetuning/task_df_giga_mind_class_dist
# task_df_name: task_df_giga_mind_interruption_3_day
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/giga_mind/finetuning/task_df_giga_mind_event_label/finetuning/task_df_giga_mind_interruption_in_seq/finetuning/task_df_giga_mind_class_dist/finetune_weights
# config:
#   is_cls_dist: false
#   is_event_classification: false
#   save_metrics: true
#   save_metrics_fp: /home/filip-marcus/results/giga_mind/event_label_interruption_in_seq_class_dist_interruption3
#   is_pretrain: false
#   attention_dropout: 0.09153289545361865
#   input_dropout: 0.3958239248386486
#   resid_dropout: 0.12879814545385304
#   is_interruption_forecast: true
#   task_specific_params:
#     pooling_method: max


# # Strategy:  (interruption in seq --> class dist --> event label --> interruption 3 day) 
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/giga_mind/finetuning/task_df_giga_mind_interruption_in_seq/finetuning/task_df_giga_mind_class_dist/finetuning/task_df_giga_mind_event_label
# task_df_name: task_df_giga_mind_interruption_3_day
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/giga_mind/finetuning/task_df_giga_mind_interruption_in_seq/finetuning/task_df_giga_mind_class_dist/finetuning/task_df_giga_mind_event_label/finetune_weights
# config:
#   is_cls_dist: false
#   is_event_classification: false
#   save_metrics: true
#   save_metrics_fp: /home/filip-marcus/results/giga_mind/interruption_in_seq_class_dist_event_label_interruption3
#   is_pretrain: false
#   attention_dropout: 0.09153289545361865
#   input_dropout: 0.3958239248386486
#   resid_dropout: 0.12879814545385304
#   is_interruption_forecast: true
#   task_specific_params:
#     pooling_method: max

# # Strategy:  (interruption in seq --> event label --> class dist --> interruption 3 day) 
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/giga_mind/finetuning/task_df_giga_mind_interruption_in_seq/finetuning/task_df_giga_mind_event_label/finetuning/task_df_giga_mind_class_dist
# task_df_name: task_df_giga_mind_interruption_3_day
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/giga_mind/finetuning/task_df_giga_mind_interruption_in_seq/finetuning/task_df_giga_mind_event_label/finetuning/task_df_giga_mind_class_dist/finetune_weights
# config:
#   is_cls_dist: false
#   is_event_classification: false
#   save_metrics: true
#   save_metrics_fp: /home/filip-marcus/results/giga_mind/interruption_in_seq_event_label_class_dist_interruption3
#   is_pretrain: false
#   attention_dropout: 0.09153289545361865
#   input_dropout: 0.3958239248386486
#   resid_dropout: 0.12879814545385304
#   is_interruption_forecast: true
#   task_specific_params:
#     pooling_method: max

data_config:
  save_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/data/processed/giga_mind_final
  max_seq_len: 256
  seq_padding_side: left

optimization_config:
  init_lr: 0.00003337824389008253
  end_lr: 6.486227076464023e-06
  end_lr_frac_of_init_lr: 0.19432499498247224
  max_epochs: 17
  batch_size: 18
  validation_batch_size: 32
  lr_frac_warmup_steps: 0.00024225416397755957
  lr_num_warmup_steps: 6
  max_training_steps: 23800
  lr_decay_power: 3.927846507579557
  weight_decay: 0.4799349316041168
  patience: null
  gradient_accumulation: 1
  gradient_clip_val: 1
  num_dataloader_workers: 5