defaults:
  - dataset_base
  - _self_

do_overwrite: True

cohort_name: "eneryield_one"
subject_id_col: "sequence_id"
raw_data_dir: "/home/filip-marcus/ESGPT_test/data/eneryield/pretrain"
save_dir: "./data/processed/${cohort_name}"

DL_chuck_size: null

inputs:
  subjects:
    input_df: "${raw_data_dir}/eneryield_subjects_one.csv"
  event:
    input_df: "${raw_data_dir}/eneryield_one_subject_small.csv"
    ts_col: "timestamp"
    ts_format: "%Y-%m-%d %H:%M:%S"
    event_type: "disturbance"
    
measurements:
  static:
    single_label_classification:
      subjects: ["dummy_static"]
  dynamic:
    multi_label_classification:
      event: ["event_label"]
    event: ["feature_0", "feature_1", "feature_2", "feature_3", "feature_4", "feature_5", "feature_6", "feature_7", "feature_8","feature_9", "feature_10"]
     
     

    
min_valid_vocab_element_observations: 2
min_valid_column_observations: 2
min_true_float_frequency: 0.1
min_unique_numerical_observations: 2
min_events_per_subject: 2
agg_by_time_scale: null