defaults:
  - dataset_base
  - _self_

# So that it can be run multiple times without issue.
do_overwrite: True

cohort_name: "megamind"
subject_id_col: "sequence_id"
raw_data_dir: "/home/filip-marcus/preprocessed_data/eneryield_ecom_mimic_pred_ecom_cosm/pretrain"
save_dir: "/home/filip-marcus/ESGPT_new/EventStreamGPT/data/processed/${cohort_name}"

DL_chunk_size: null

inputs:
  subjects:
    input_df: "${raw_data_dir}/subjects.csv"
  eneryield:
    input_df: "${raw_data_dir}/eneryield.csv"
    ts_col: "timestamp"
    ts_format: "%Y-%m-%d %H:%M:%S"
    event_type: "eneryield"
  ecom_electronic:
    input_df: "${raw_data_dir}/ecom.csv"
    ts_col: "event_time"
    ts_format: "%Y-%m-%d %H:%M:%S"
    event_type: "ecom_electronic"
  ecom_cosmetic:
    input_df: "${raw_data_dir}/ecom_cosm.csv"
    ts_col: "event_time"
    ts_format: "%Y-%m-%d %H:%M:%S"
    event_type: "ecom_cosmetic"
  predictive_maintenance:
    input_df: "${raw_data_dir}/pred.csv" # h책ll koll p책 stavning
    ts_col: "date"
    ts_format: "%m/%d/%Y"
    event_type: "predictive_maintenance"
  mimic_edstays:
    input_df: "${raw_data_dir}/df_mimic_edstays.csv"
    start_ts_col: "intime"
    end_ts_col: "outtime"
    ts_format: "%Y-%m-%d %H:%M:%S"
    event_type: "mimic_edstays"
  mimic_medrecon:
    input_df: "${raw_data_dir}/df_mimic_medrecon.csv"
    ts_col: "charttime"
    ts_format: "%Y-%m-%d %H:%M:%S"
    event_type: "mimic_medrecon"
  mimic_pyxis:
    input_df: "${raw_data_dir}/df_mimic_pyxis.csv"
    ts_col: "charttime"
    ts_format: "%Y-%m-%d %H:%M:%S"
    event_type: "mimic_pyxis"
  mimic_vitalsign:
    input_df: "${raw_data_dir}/df_mimic_vitalsign.csv"
    ts_col: "charttime"
    ts_format: "%Y-%m-%d %H:%M:%S"
    event_type: "mimic_vitalsign"

measurements:
  static:
    single_label_classification:
      subjects: ["dummy_static"]
  dynamic:
    multi_label_classification:
      eneryield: ["event_label"]
      ecom_electronic: ["event_label"] #["event_label", "brand", "product_id", "category_id", "category_code"]
      ecom_cosmetic: ["event_label"] # ["event_label", "brand", "product_id", "category_id", "category_code"]
      vitalsign: ["rhythm", "pain"]
      # medrecon: ["name"]
      edstays: ["arrival_transport", "disposition"]  
    univariate_regression:
      ecom_electronic: ["price"]
      ecom_cosmetic: ["price"]
      vitalsign: ["heartrate", "resprate", "o2sat", "sbp", "dbp", "temperature"]
  
    # l채gg till mer h채r


min_valid_vocab_element_observations: 2
min_valid_column_observations: 2
min_true_float_frequency: 0.1
min_unique_numerical_observations: 2
min_events_per_subject: 0
agg_by_time_scale: null
