defaults:
  - dataset_base
  - _self_

do_overwrite: True

cohort_name: "synthetic_1"
subject_id_col: "sequence_id"
raw_data_dir: "/home/filip-marcus/preprocessed_data/synthetic/pretrain"
save_dir: "./data/processed/${cohort_name}"

DL_chuck_size: null

# inputs:
#   subjects:
#     input_df: "${raw_data_dir}/synthetic_subjects_1.csv"
#   event_synthetic_1:
#     input_df: "${raw_data_dir}/synthetic_dataset_1.csv"
#     ts_col: "timestamp"
#     ts_format: "%Y-%m-%d %H:%M:%S"
#     event_type: "disturbance"

    
# measurements:
#   static:
#     single_label_classification:
#       subjects: ["dummy_static"]
#   dynamic:
#     multi_label_classification:
#       event_synthetic_1: ["event_label"]
#     univariate_regression:
#       event_synthetic_1: ["feature_vector"]



inputs:
  subjects:
    input_df: "${raw_data_dir}/synthetic_subjects_1.csv"
  simple_event:
    input_df: "${raw_data_dir}/synthetic_dataset_1.csv"
    ts_col: "timestamp"
    ts_format: "%Y-%m-%d %H:%M:%S"
    event_type: "simple_event"

    
measurements:
  static:
    single_label_classification:
      subjects: ["dummy_static"]
  dynamic:
    multi_label_classification:
      simple_event: ["event_label"]
    univariate_regression:
      simple_event: ["feature_1"]


     
     

    
min_valid_vocab_element_observations: 2
min_valid_column_observations: 2
min_true_float_frequency: 0.1
min_unique_numerical_observations: 2
min_events_per_subject: 2
agg_by_time_scale: null