defaults:
  - finetune_config
  - _self_

do_overwrite: true
seed: 1


# Strategy:  (event label) DONE!
load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield2/
task_df_name: task_df_eneryield_event_label
pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield2/pretrained_weights
config:
  is_cls_dist: false
  is_event_classification: true
  save_metrics: true
  save_metrics_fp: /home/filip-marcus/results/eneryield2/event_label_baseline


# # Strategy:  (event label) 
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield2/
# task_df_name: task_df_eneryield_interruption_in_seq
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield2/pretrained_weights
# config:
#   is_cls_dist: true
#   is_event_classification: false
#   save_metrics: true
#   save_metrics_fp: /home/filip-marcus/results/test/test2


# # Strategy:  (event label --> interruption in seq) 
# strategy: true
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield2/finetuning/task_df_eneryield_event_label
# task_df_name: task_df_eneryield_interruption_in_seq
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield2/finetuning/task_df_eneryield_event_label/finetune_weights
# config:
#   is_cls_dist: false
#   is_event_classification: false

# # Strategy:  (event label --> interruption in seq --> interruptin next week) 
# strategy: true
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield/2finetuning/task_df_eneryield_event_label/task_df_eneryield_interruption_in_seq
# task_df_name: task_df_eneryield_interruption_next_week
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield2/finetuning/task_df_eneryield_event_label/task_df_eneryield_interruption_in_seq/finetune_weights
# config:
#   is_cls_dist: false
#   is_event_classification: false


data_config:
  save_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/data/processed/eneryield2
  max_seq_len: 256
optimization_config:
  batch_size: 22
  end_lr: 0.0007880591344790904
  end_lr_frac_of_init_lr: 0.35519807160495326
  gradient_accumulation: 1
  gradient_clip_val: 1
  init_lr: 0.002218646995796643
  lr_decay_power: 3.210658795131431
  lr_frac_warmup_steps: 0.03027953662752261
  lr_num_warmup_steps: 297
  max_epochs: 55
  max_training_steps: 9800
  num_dataloader_workers: 5
  patience: null
  validation_batch_size: 32
  weight_decay: 0.0008206802576053819




    # init_lr: 0.002846394145333227
    # end_lr: 2.3329478071180696e-05
    # end_lr_frac_of_init_lr: 0.008196151650125572
    # max_epochs: 200
    # batch_size: 12
    # validation_batch_size: 32
    # lr_frac_warmup_steps: 3.5555186373837375e-06
    # lr_num_warmup_steps: 0
    # max_training_steps: 2800
    # lr_decay_power: 1.4708137696434
    # weight_decay: 0.00847623042952091
    # patience: 10
    # gradient_accumulation: 1
    # gradient_clip_val: 1
    # num_dataloader_workers: 5