defaults:
  - finetune_config
  - _self_

do_overwrite: true
seed: 1

# # Strategy:  (event label) DONE!
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield/
# task_df_name: task_df_eneryield_event_label
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield/pretrained_weights
# config:
#   is_cls_dist: false
#   is_event_classification: true


# Strategy:  (event label) DONE!
load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield/
task_df_name: task_df_eneryield_class_dist
pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield/pretrained_weights
config:
  is_cls_dist: true
  is_event_classification: false

# # Strategy:  (event label --> interruption in seq) 
# strategy: true
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield/finetuning/task_df_eneryield_event_label
# task_df_name: task_df_eneryield_interruption_in_seq
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield/finetuning/task_df_eneryield_event_label/finetune_weights
# config:
#   is_cls_dist: false
#   is_event_classification: false

# # Strategy:  (event label --> interruption in seq --> interruptin next week) 
# strategy: true
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield/finetuning/task_df_eneryield_event_label/task_df_eneryield_interruption_in_seq
# task_df_name: task_df_eneryield_interruption_next_week
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield/finetuning/task_df_eneryield_event_label/task_df_eneryield_interruption_in_seq/finetune_weights
# config:
#   is_cls_dist: false
#   is_event_classification: false


# # Strategy:  (event label --> interruption in seq --> interruptin next week --> class distribution) 
# strategy: true
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield/finetuning/task_df_eneryield_event_label/task_df_eneryield_interruption_in_seq/task_df_eneryield_interruption_next_week
# task_df_name: task_df_eneryield_class_dist
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield/finetuning/task_df_eneryield_event_label/task_df_eneryield_interruption_in_seq/task_df_eneryield_interruption_next_week/finetune_weights
# config:
#   is_cls_dist: true
#   is_event_classification: false

# # Strategy:  (event label --> interruption in seq --> interruptin next week --> class distribution) 
# strategy: true
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_event_label/task_df_synthetic_interruption_in_seq/task_df_synthetic_interruption_next_week/task_df_synthetic_class_dist
# task_df_name: task_df_synthetic_tti
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_event_label/task_df_synthetic_interruption_in_seq/task_df_synthetic_interruption_next_week/task_df_synthetic_class_dist/finetune_weights
# config:
#   is_cls_dist: false
#   is_event_classification: false


# # Strategy: 2 (class distribution) DONE!
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/
# task_df_name: task_df_synthetic_class_dist
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/pretrained_weights
# config:
#   is_cls_dist: true

# # Strategy: 3 (interruption next week) DONE!
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/
# task_df_name: task_df_synthetic_interruption_next_week
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/pretrained_weights

# # Strategy: 1->2 (interruption in seq --> class distribution) DONE!
# strategy: true
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_interruption_in_seq
# task_df_name: task_df_synthetic_class_dist
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_interruption_in_seq/finetune_weights
# config:
#   is_cls_dist: true

# # Strategy: 1->3 (interruption in seq --> interruption in next week) DONE!
# strategy: true
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_interruption_in_seq
# task_df_name: task_df_synthetic_interruption_next_week
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_interruption_in_seq/finetune_weights

# # Strategy: 1->2->3 (interruption in seq --> class distribution --> interruption next week) DONE!
# strategy: true
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_interruption_in_seq/task_df_synthetic_class_dist
# task_df_name: task_df_synthetic_interruption_next_week
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_interruption_in_seq/task_df_synthetic_class_dist/finetune_weights
# config:
#   is_cls_dist: false

# # Strategy: 1->3->2 (interruption in seq --> interruption next week --> class distribution) DONE!
# strategy: true
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_interruption_in_seq/task_df_synthetic_interruption_next_week
# task_df_name: task_df_synthetic_class_dist
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_interruption_in_seq/task_df_synthetic_interruption_next_week/finetune_weights


# # Strategy: 1->2->3->4 (interruption in seq --> class distribution --> interruption next week --> TTI) 
# strategy: true
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_interruption_in_seq/task_df_synthetic_class_dist/task_df_synthetic_interruption_next_week
# task_df_name: task_df_synthetic_tti
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_interruption_in_seq/task_df_synthetic_class_dist/task_df_synthetic_interruption_next_week/finetune_weights
# config:
#   is_cls_dist: false

# # Strategy: 1->2->4 (interruption in seq --> class distribution  --> TTI) 
# strategy: true
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_interruption_in_seq/task_df_synthetic_class_dist
# task_df_name: task_df_synthetic_tti
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_interruption_in_seq/task_df_synthetic_class_dist/finetune_weights

# # Strategy: 1->2->4->3 (interruption in seq --> class distribution  --> TTI --> interruption next week ) 
# strategy: true
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_interruption_in_seq/task_df_synthetic_class_dist/task_df_synthetic_tti
# task_df_name: task_df_synthetic_interruption_next_week
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_interruption_in_seq/task_df_synthetic_class_dist/task_df_synthetic_tti/finetune_weights

# # Strategy: 1->3->2->4 (interruption in seq --> interruption next week --> class distribution --> TTI)DONE!
# strategy: true
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_interruption_in_seq/task_df_synthetic_interruption_next_week/task_df_synthetic_class_dist
# task_df_name: task_df_synthetic_tti
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_interruption_in_seq/task_df_synthetic_interruption_next_week/task_df_synthetic_class_dist/finetune_weights

# # Strategy: 2->1 (class distribution --> interruption in seq ) 
# strategy: true
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_class_dist
# task_df_name: task_df_synthetic_interruption_in_seq
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_class_dist/finetune_weights

# # Strategy: 2->3 (class distribution --> interruption next week ) DONE!
# strategy: true
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_class_dist
# task_df_name: task_df_synthetic_interruption_next_week
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_class_dist/finetune_weights

# # Strategy: 2->1->3 (class distribution --> interruption in seq --> interruption next week ) DONE!
# strategy: true
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_class_dist/task_df_synthetic_interruption_in_seq
# task_df_name: task_df_synthetic_interruption_next_week
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_class_dist/task_df_synthetic_interruption_in_seq/finetune_weights

# # Strategy: 2->3->1 (class distribution --> interruption next week --> interruption in seq) DONE!
# strategy: true
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_class_dist/task_df_synthetic_interruption_next_week
# task_df_name: task_df_synthetic_interruption_in_seq
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_class_dist/task_df_synthetic_interruption_next_week/finetune_weights

# # Strategy: 2->1->3->4 (class distribution --> interruption in seq --> interruption next week --> TTI )DONE!
# strategy: true
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_class_dist/task_df_synthetic_interruption_in_seq/task_df_synthetic_interruption_next_week
# task_df_name: task_df_synthetic_tti
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_class_dist/task_df_synthetic_interruption_in_seq/task_df_synthetic_interruption_next_week/finetune_weights

# # Strategy: 2->3->1->4 (class distribution --> interruption next week --> interruption in seq --> TTI)DONE!
# strategy: true
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_class_dist/task_df_synthetic_interruption_next_week/task_df_synthetic_interruption_in_seq
# task_df_name: task_df_synthetic_tti
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_class_dist/task_df_synthetic_interruption_next_week/task_df_synthetic_interruption_in_seq/finetune_weights

# # Strategy: 3->1 (interruption next week --> interruption in seq )DONE!
# strategy: true
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_interruption_next_week
# task_df_name: task_df_synthetic_interruption_in_seq
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_interruption_next_week/finetune_weights

# # Strategy: 3->2 (interruption next week --> class distribution )DONE!
# strategy: true
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_interruption_next_week
# task_df_name: task_df_synthetic_class_dist
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_interruption_next_week/finetune_weights

# # Strategy: 3->1->2 (interruption next week --> interruption in seq --> class distrbution)DONE!
# strategy: true
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_interruption_next_week/task_df_synthetic_interruption_in_seq
# task_df_name: task_df_synthetic_class_dist
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_interruption_next_week/task_df_synthetic_interruption_in_seq/finetune_weights

# # Strategy: 3->2->1 (interruption next week --> class distribution --> interruption in seq)DONE!
# strategy: true
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_interruption_next_week/task_df_synthetic_class_dist
# task_df_name: task_df_synthetic_interruption_in_seq
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_interruption_next_week/task_df_synthetic_class_dist/finetune_weights

# # Strategy: 3->1->2->4 (interruption next week --> interruption in seq --> class distrbution --> TTI)DONE!
# strategy: true
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_interruption_next_week/task_df_synthetic_interruption_in_seq/task_df_synthetic_class_dist
# task_df_name: task_df_synthetic_tti
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_interruption_next_week/task_df_synthetic_interruption_in_seq/task_df_synthetic_class_dist/finetune_weights

# # Strategy: 3->2->1->4 (interruption next week --> class distribution --> interruption in seq --> TTI)DONE!
# strategy: true
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_interruption_next_week/task_df_synthetic_class_dist/task_df_synthetic_interruption_in_seq
# task_df_name: task_df_synthetic_tti
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_interruption_next_week/task_df_synthetic_class_dist/task_df_synthetic_interruption_in_seq/finetune_weights

data_config:
  save_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/data/processed/eneryield
  max_seq_len: 128
optimization_config:
  init_lr: 0.0001 #0.0006398098082729676
  end_lr: 0.0000999999 #8.05022482949952e-06
  end_lr_frac_of_init_lr: null
  max_epochs: 200
  batch_size: 32
  validation_batch_size: 32
  lr_frac_warmup_steps: 6.821087018693635e-06
  lr_num_warmup_steps: 0
  max_training_steps: 6000 #100
  lr_decay_power: 0 #2 #4.915424972614257
  weight_decay: 0.000001 #0.927050268775883
  patience: null
  gradient_accumulation: 2
  gradient_clip_val: 1
  num_dataloader_workers: 5
