defaults:
  - finetune_config
  - _self_

do_overwrite: true
seed: 1

# Strategy:  (class dist)
load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield/
task_df_name: task_df_eneryield_interruption_7_day
pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield/pretrained_weights
config:
  is_cls_dist: false
  is_event_classification: false
  save_metrics: true
  save_metrics_fp: /home/filip-marcus/results/eneryield/interruption_in_seq_baseline

data_config:
  save_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/data/processed/eneryield
  max_seq_len: 256

optimization_config:
  init_lr: 0.0005387192471114002
  end_lr: 2.524466419119271e-06
  end_lr_frac_of_init_lr: 0.004686052025531666
  max_epochs: 200
  batch_size: 63
  validation_batch_size: 32
  lr_frac_warmup_steps: 0.2670639865238901
  lr_num_warmup_steps: 160
  max_training_steps: 600
  lr_decay_power: 0.9032979645205408
  weight_decay: 0.2821793603431732
  patience: 15
  gradient_accumulation: 1
  gradient_clip_val: 1
  num_dataloader_workers: 5