defaults:
  - parameters: finetuning
  - _self_

entity: marcus-student-chalmers-personal
project: eneryield_ft_sweep
program: finetune.py
method: bayes
name: event_label
metric:
  goal: minimize
  name: task_loss
early_terminate:
  type: hyperband
  min_iter: 1000
# log_every_n_steps: 2

parameters:
  do_overwrite: 
    value: true
  config:
    is_cls_dist: 
      value: false
    is_event_classification: 
      value: true
  optimization_config:
    num_dataloader_workers:
      value: 5

    patience:
      value: 8
    init_lr:
      max: 1
      min: 1e-8
    weight_decay:
      max: 0.01
      min: 0.00000000001
    max_epochs:
      value: 200
    batch_size:
      max: 64
      min: 8
  task_df_name: 
    value: task_df_eneryield_event_label
  load_from_model_dir: 
    value: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield/
  seed: 
    value: 1
  pretrained_weights_fp: 
    value: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield/pretrained_weights

  data_config:
    save_dir: 
      value: /home/filip-marcus/ESGPT_new/EventStreamGPT/data/processed/eneryield
