defaults:
  - pretraining_hyperparameter_sweep_base # IMPORTANT: This defaults to the pre-defined repository config!
  - _self_

parameters:
  experiment_dir:
    value: /home/filip-marcus/ESGPT_new/EventStreamGPT
  data_config:
    save_dir:
      value: /home/filip-marcus/ESGPT_new/EventStreamGPT/data/processed/eneryield
    max_seq_len: 
      max: 256
      min: 128
  config:
    measurements_per_dep_graph_level:
      values: null
    head_dim: 
      value: 18
    hidden_size:
      value: 180
    structured_event_processing_mode:
      values: ["conditionally_independent"]
    intermediate_size:
      value: 128
    num_attention_heads:
      value: 10
    num_hidden_layers:
      value: 8
    seq_attention_types:
      values: ['global']
    static_embedding_mode:
      values: ['drop']
    do_split_embeddings:
      values: [False]    
  optimization_config:
    num_dataloader_workers:
      value: 5
    max_epochs:
      value: 50
    patience: 
      value: 5
    batch_size:
      max: 64
      min: 8
    weight_decay:
      max: 0.01
      min: 0.0000000001
  trainer_config:
    log_every_n_steps:
      value: 20

    
  
  do_overwrite: 
    value: True 

entity: "marcus-student-chalmers"
project: "Hyperparameter_sweep_eneryield"
run_cap: 30


