defaults:
  - dataset_base
  - _self_

do_overwrite: True

cohort_name: "eneryield_event_type"
subject_id_col: "sequence_id"
raw_data_dir: "/home/filip-marcus/ESGPT_test/data/eneryield/pretrain"
save_dir: "./data/processed/${cohort_name}"

DL_chuck_size: null

inputs:
  subjects:
    input_df: "${raw_data_dir}/subjects_eneryield.csv"
  events_VD:
    input_df: "${raw_data_dir}/df_VD.csv"
    ts_col: "timestamp"
    ts_format: "%Y-%m-%d %H:%M:%S"
    event_type: "VD"
  events_transient:
    input_df: "${raw_data_dir}/df_transient.csv"
    ts_col: "timestamp"
    ts_format: "%Y-%m-%d %H:%M:%S"
    event_type: "transient"
  events_interruption:
    input_df: "${raw_data_dir}/df_interruption.csv"
    ts_col: "timestamp"
    ts_format: "%Y-%m-%d %H:%M:%S"
    event_type: "interruption"
  events_unbalance_u:
    input_df: "${raw_data_dir}/df_unbalance_u.csv"
    ts_col: "timestamp"
    ts_format: "%Y-%m-%d %H:%M:%S"
    event_type: "unbalance_u"
  events_current_deviation:
    input_df: "${raw_data_dir}/df_current_deviation.csv"
    ts_col: "timestamp"
    ts_format: "%Y-%m-%d %H:%M:%S"
    event_type: "current_deviation"
  events_harmonics_i:
    input_df: "${raw_data_dir}/df_harmonics_i.csv"
    ts_col: "timestamp"
    ts_format: "%Y-%m-%d %H:%M:%S"
    event_type: "harmonics_i"
  events_harmonics_u:
    input_df: "${raw_data_dir}/df_harmonics_u.csv"
    ts_col: "timestamp"
    ts_format: "%Y-%m-%d %H:%M:%S"
    event_type: "harmonics_u"
  events_unbalance_i:
    input_df: "${raw_data_dir}/df_unbalance_i.csv"
    ts_col: "timestamp"
    ts_format: "%Y-%m-%d %H:%M:%S"
    event_type: "unbalance_i"

measurements:
  static:
    single_label_classification:
      subjects: ["dummy_static"]
  dynamic:
    multi_label_classification:
      events_VD: ["event_label"]
      events_interruption: ["event_label"]
      events_transient: ["event_label"]
      events_unbalance_u: ["event_label"]
      events_unbalance_i: ["event_label"]
      events_harmonics_u: ["event_label"]
      events_harmonics_i: ["event_label"]
      events_current_deviation: ["event_label"]
    univariate_regression:
      events_VD: ["feature_0", "feature_1", "feature_2", "feature_3", "feature_4", "feature_5", "feature_6", "feature_7", "feature_8","feature_9", "feature_10", "feature_11", "feature_12", "feature_13", "feature_14", "feature_15", "feature_16", "feature_17", "feature_18","feature_19", "feature_20", "feature_21", "feature_22", "feature_23", "feature_24", "feature_25", "feature_26", "feature_27", "feature_28","feature_29", "feature_30", "feature_31", "feature_32", "feature_33", "feature_34", "feature_35", "feature_36", "feature_37", "feature_38","feature_39", "feature_40", "feature_41", "feature_42", "feature_43", "feature_44", "feature_45", "feature_46", "feature_47", "feature_48"]
      events_interruption: ["feature_0", "feature_1", "feature_2", "feature_3", "feature_4", "feature_5", "feature_6", "feature_7", "feature_8","feature_9", "feature_10", "feature_11", "feature_12", "feature_13", "feature_14", "feature_15", "feature_16", "feature_17", "feature_18","feature_19", "feature_20", "feature_21", "feature_22", "feature_23", "feature_24", "feature_25", "feature_26", "feature_27", "feature_28","feature_29", "feature_30", "feature_31", "feature_32", "feature_33", "feature_34", "feature_35", "feature_36", "feature_37", "feature_38","feature_39", "feature_40", "feature_41", "feature_42", "feature_43", "feature_44", "feature_45", "feature_46", "feature_47", "feature_48"]
      events_transient: ["feature_0", "feature_1", "feature_2", "feature_3", "feature_4", "feature_5", "feature_6", "feature_7", "feature_8","feature_9", "feature_10", "feature_11", "feature_12", "feature_13", "feature_14", "feature_15", "feature_16", "feature_17", "feature_18","feature_19", "feature_20", "feature_21", "feature_22", "feature_23", "feature_24", "feature_25", "feature_26", "feature_27", "feature_28","feature_29", "feature_30", "feature_31", "feature_32", "feature_33", "feature_34", "feature_35", "feature_36", "feature_37", "feature_38","feature_39", "feature_40", "feature_41", "feature_42", "feature_43", "feature_44", "feature_45", "feature_46", "feature_47", "feature_48"]
      events_unbalance_u: ["feature_0", "feature_1", "feature_2", "feature_3", "feature_4", "feature_5", "feature_6", "feature_7", "feature_8","feature_9", "feature_10", "feature_11", "feature_12", "feature_13", "feature_14", "feature_15", "feature_16", "feature_17", "feature_18","feature_19", "feature_20", "feature_21", "feature_22", "feature_23", "feature_24", "feature_25", "feature_26", "feature_27", "feature_28","feature_29", "feature_30", "feature_31", "feature_32", "feature_33", "feature_34", "feature_35", "feature_36", "feature_37", "feature_38","feature_39", "feature_40", "feature_41", "feature_42", "feature_43", "feature_44", "feature_45", "feature_46", "feature_47", "feature_48"]
      events_unbalance_i: ["feature_0", "feature_1", "feature_2", "feature_3", "feature_4", "feature_5", "feature_6", "feature_7", "feature_8","feature_9", "feature_10", "feature_11", "feature_12", "feature_13", "feature_14", "feature_15", "feature_16", "feature_17", "feature_18","feature_19", "feature_20", "feature_21", "feature_22", "feature_23", "feature_24", "feature_25", "feature_26", "feature_27", "feature_28","feature_29", "feature_30", "feature_31", "feature_32", "feature_33", "feature_34", "feature_35", "feature_36", "feature_37", "feature_38","feature_39", "feature_40", "feature_41", "feature_42", "feature_43", "feature_44", "feature_45", "feature_46", "feature_47", "feature_48"]
      events_harmonics_u: ["feature_0", "feature_1", "feature_2", "feature_3", "feature_4", "feature_5", "feature_6", "feature_7", "feature_8","feature_9", "feature_10", "feature_11", "feature_12", "feature_13", "feature_14", "feature_15", "feature_16", "feature_17", "feature_18","feature_19", "feature_20", "feature_21", "feature_22", "feature_23", "feature_24", "feature_25", "feature_26", "feature_27", "feature_28","feature_29", "feature_30", "feature_31", "feature_32", "feature_33", "feature_34", "feature_35", "feature_36", "feature_37", "feature_38","feature_39", "feature_40", "feature_41", "feature_42", "feature_43", "feature_44", "feature_45", "feature_46", "feature_47", "feature_48"]
      events_harmonics_i: ["feature_0", "feature_1", "feature_2", "feature_3", "feature_4", "feature_5", "feature_6", "feature_7", "feature_8","feature_9", "feature_10", "feature_11", "feature_12", "feature_13", "feature_14", "feature_15", "feature_16", "feature_17", "feature_18","feature_19", "feature_20", "feature_21", "feature_22", "feature_23", "feature_24", "feature_25", "feature_26", "feature_27", "feature_28","feature_29", "feature_30", "feature_31", "feature_32", "feature_33", "feature_34", "feature_35", "feature_36", "feature_37", "feature_38","feature_39", "feature_40", "feature_41", "feature_42", "feature_43", "feature_44", "feature_45", "feature_46", "feature_47", "feature_48"]
      events_current_deviation: ["feature_0", "feature_1", "feature_2", "feature_3", "feature_4", "feature_5", "feature_6", "feature_7", "feature_8","feature_9", "feature_10", "feature_11", "feature_12", "feature_13", "feature_14", "feature_15", "feature_16", "feature_17", "feature_18","feature_19", "feature_20", "feature_21", "feature_22", "feature_23", "feature_24", "feature_25", "feature_26", "feature_27", "feature_28","feature_29", "feature_30", "feature_31", "feature_32", "feature_33", "feature_34", "feature_35", "feature_36", "feature_37", "feature_38","feature_39", "feature_40", "feature_41", "feature_42", "feature_43", "feature_44", "feature_45", "feature_46", "feature_47", "feature_48"]




min_valid_vocab_element_observations: 2
min_valid_column_observations: 2
min_true_float_frequency: 0.1
min_unique_numerical_observations: 49

min_events_per_subject: 0
agg_by_time_scale: null

