defaults:
  - finetune_config
  - _self_

seed: 1


# Strategy: pretrain
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/
# task_df_name: task_df_synthetic_tti
#pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/pretrained_weights

# # Strategy: 1 (interruption in seq)
# strategy: true
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_interruption_in_seq
# task_df_name: task_df_synthetic_tti
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_interruption_in_seq/finetune_weights

# # Strategy: 1->2 (interruption in seq --> class distribution)
# strategy: true
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_interruption_in_seq/task_df_synthetic_class_dist
# task_df_name: task_df_synthetic_tti
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_interruption_in_seq/task_df_synthetic_class_dist/finetune_weights

# # Strategy: 1->3 (interruption in seq --> interruption in next week)
# strategy: true
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_interruption_in_seq/task_df_synthetic_interruption_next_week
# task_df_name: task_df_synthetic_tti
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_interruption_in_seq/task_df_synthetic_interruption_next_week/finetune_weights


# # Strategy: 1->2->3 (interruption in seq  --> class distribution --> interruption in next week)
# strategy: true
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_interruption_in_seq/task_df_synthetic_class_dist/task_df_synthetic_interruption_next_week
# task_df_name: task_df_synthetic_tti
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_interruption_in_seq/task_df_synthetic_class_dist/task_df_synthetic_interruption_next_week/finetune_weights

# Strategy: 1->3->2 (interruption in seq --> interruption in next week --> class distribution)
# strategy: true
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_interruption_in_seq/task_df_synthetic_interruption_next_week/task_df_synthetic_class_dist
# task_df_name: task_df_synthetic_tti
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_interruption_in_seq/task_df_synthetic_interruption_next_week/task_df_synthetic_class_dist/finetune_weights

# Strategy: 1->2->3->4 (interruption in seq  --> class distribution --> interruption in next week --> TTI)
strategy: true
load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_interruption_in_seq/task_df_synthetic_class_dist/task_df_synthetic_interruption_next_week/task_df_synthetic_tti
task_df_name: task_df_synthetic_tti
pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_interruption_in_seq/task_df_synthetic_class_dist/task_df_synthetic_interruption_next_week/task_df_synthetic_tti/finetune_weights

# Strategy: 1->3->2->4 (interruption in seq --> interruption in next week --> class distribution --> TTI)
# strategy: true
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_interruption_in_seq/task_df_synthetic_interruption_next_week/task_df_synthetic_class_dist/task_df_synthetic_tti
# task_df_name: task_df_synthetic_tti
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_interruption_in_seq/task_df_synthetic_interruption_next_week/task_df_synthetic_class_dist/task_df_synthetic_tti/finetune_weights


# # Strategy: 2->1 (class distribution --> interruption in seq )
# strategy: true
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_class_dist/task_df_interruption_in_seq
# task_df_name: task_df_synthetictti
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_class_dist/task_df_interruption_in_seq/finetune_weights

# # Strategy: 2->3 (class distribution --> interruption next week )
# strategy: true
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_class_dist/task_df_synthetic_interruption_next_week
# task_df_name: task_df_synthetic_tti
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_class_dist/task_df_synthetic_interruption_next_week/finetune_weights

# # Strategy: 2->1->3 (class distribution --> interruption in seq --> interruption next week )
# strategy: true
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_class_dist/task_df_synthetic_interruption_in_seq/task_df_synthetic_interruption_next_week
# task_df_name: task_df_synthetic_tti
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_class_dist/task_df_synthetic_interruption_in_seq/task_df_synthetic_interruption_next_week/finetune_weights

# # Strategy: 2->3->1 (class distribution --> interruption next week --> interruption in seq)
# strategy: true
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_class_dist/task_df_synthetic_interruption_next_week/task_df_synthetic_interruption_in_seq
# task_df_name: task_df_synthetic_tti
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_class_dist/task_df_synthetic_interruption_next_week/task_df_synthetic_interruption_in_seq/finetune_weights

# # Strategy: 2->1->3->4 (class distribution --> interruption in seq --> interruption next week --> TTI )
# strategy: true
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_class_dist/task_df_synthetic_interruption_in_seq/task_df_synthetic_interruption_next_week/task_df_synthetic_tti
# task_df_name: task_df_synthetic_tti
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_class_dist/task_df_synthetic_interruption_in_seq/task_df_synthetic_interruption_next_week/task_df_synthetic_tti/finetune_weights

# # Strategy: 2->3->1->4 (class distribution --> interruption next week --> interruption in seq --> TTI)
# strategy: true
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_class_dist/task_df_synthetic_interruption_next_week/task_df_synthetic_interruption_in_seq/task_df_synthetic_tti
# task_df_name: task_df_synthetic_tti
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_class_dist/task_df_synthetic_interruption_next_week/task_df_synthetic_interruption_in_seq/task_df_synthetic_tti/finetune_weights


# # Strategy: 3->1 (interruption next week --> interruption in seq )
# strategy: true
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_interruption_next_week/task_df_synthetic_interruption_in_seq
# task_df_name: task_df_synthetic_tti
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_interruption_next_week/task_df_synthetic_interruption_in_seq/finetune_weights

# # Strategy: 3->2 (interruption next week --> class distribution )
# strategy: true
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_interruption_next_week/task_df_synthetic_class_dist
# task_df_name: task_df_synthetic_tti
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_interruption_next_week/task_df_synthetic_class_dist/finetune_weights

# # Strategy: 3->1->2 (interruption next week --> interruption in seq --> class distrbution)
# strategy: true
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_interruption_next_week/task_df_synthetic_interruption_in_seq/task_df_synthetic_class_dist
# task_df_name: task_df_synthetic_tti
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_interruption_next_week/task_df_synthetic_interruption_in_seq/task_df_synthetic_class_dist/finetune_weights

# # Strategy: 3->2->1 (interruption next week --> class distribution --> interruption in seq)
# strategy: true
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_interruption_next_week/task_df_synthetic_class_dist/task_df_synthetic_interruption_in_seq
# task_df_name: task_df_synthetic_tti
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_interruption_next_week/task_df_synthetic_class_dist/task_df_synthetic_interruption_in_seq/finetune_weights

# # Strategy: 3->1->2->4 (interruption next week --> interruption in seq --> class distrbution --> TTI)
# strategy: true
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_interruption_next_week/task_df_synthetic_interruption_in_seq/task_df_synthetic_class_dist/task_df_synthetic_tti
# task_df_name: task_df_synthetic_tti
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_interruption_next_week/task_df_synthetic_interruption_in_seq/task_df_synthetic_class_dist/task_df_synthetic_tti/finetune_weights

# # Strategy: 3->2->1->4 (interruption next week --> class distribution --> interruption in seq --> TTI)
# strategy: true
# load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_interruption_next_week/task_df_synthetic_class_dist/task_df_synthetic_interruption_in_seq/task_df_synthetic_tti
# task_df_name: task_df_synthetic_tti
# pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/synthetic_1/finetuning/task_df_synthetic_interruption_next_week/task_df_synthetic_class_dist/task_df_synthetic_interruption_in_seq/task_df_synthetic_tti/finetune_weights

data_config:
  save_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/data/processed/synthetic_1
  max_seq_len: 409
  do_include_start_time_min: true
  seq_padding_side: left
