defaults:
  - pretrain_config
  - _self_

experiment_dir: /home/filip-marcus/models/ESGPT_new/EventStreamGPT
do_overwrite: True
data_config:
  save_dir: /home/filip-marcus/models/ESGPT_new/EventStreamGPT/data/processed/synthetic
  train_subset_size: FULL

optimization_config:
  num_dataloader_workers: 5
  max_epochs: 100
  init_lr: 0.08 
  end_lr: 0.00008
  lr_decay_power: 0


config:
  TTE_generation_layer_type: exponential
  cohort_name: synthetic
  max_seq_len: 500
  seq_attention_types: "global"
  do_full_block_in_seq_attention: True

