defaults:
  - pretrain_config
  - _self_

experiment_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT
do_overwrite: True
data_config:
  save_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/data/processed/synthetic_mega

optimization_config:
  num_dataloader_workers: 5
  max_epochs: 100
  batch_size: 128


# denna används för att spara ner output från pretraining till samma mapp, istället för att göra ny mapp varje körning
config:
  head_dim: 20
  hidden_size: 200
  num_attention_heads: 10
  intermediate_size: 128
  structured_event_processing_mode: conditionally_independent
  num_hidden_layers: 8
  max_seq_length: 256
  cohort_name: synthetic_mega