defaults:
  - pretrain_config
  - _self_

experiment_dir: /home/filip-marcus/models/ESGPT_new/EventStreamGPT
do_overwrite: True
data_config:
  save_dir: /home/filip-marcus/models/ESGPT_new/EventStreamGPT/data/processed/mimic

optimization_config:
  num_dataloader_workers: 5
  max_epochs: 2


# denna används för att spara ner output från pretraining till samma mapp, istället för att göra ny mapp varje körning
config:
  cohort_name: mimic

