defaults:
  - pretrain_config
  - _self_

experiment_dir: /home/filip-marcus/models/ESGPT_new/EventStreamGPT

do_overwrite: True
data_config:
  save_dir: /home/filip-marcus/models/ESGPT_new/EventStreamGPT/data/processed/eneryield_ecom_pred_event_type

optimization_config:
  num_dataloader_workers: 5
  batch_size: 128

config:
  head_dim: 16
  hidden_size: 160
  num_attention_heads: 10
  intermediate_size: 128
  structured_event_processing_mode: conditionally_independent
  num_hidden_layers: 8
  max_seq_length: 256
  cohort_name: eneryield_ecom_pred_event_type