defaults:
  - finetune_config
  - _self_

do_overwrite: true
seed: 1
is_inference: true # Flag to indicate that this is an inference run
task_type: interruption # Task type for the inference run - used to use the appropirate evaluation metrics

# Strategy:  (class dist)
load_from_model_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield2/finetuning/task_df_eneryield_interruption_1_day
task_df_name: task_df_eneryield_interruption_1_day
pretrained_weights_fp: /home/filip-marcus/ESGPT_new/EventStreamGPT/pretrain/eneryield2/finetuning/task_df_eneryield_interruption_1_day/finetune_weights
config:
  is_cls_dist: false
  is_event_classification: false
  save_metrics: true
  save_metrics_fp: /home/filip-marcus/results/eneryield2/interruption_1_day_baseline

data_config:
  save_dir: /home/filip-marcus/ESGPT_new/EventStreamGPT/data/processed/eneryield2
  max_seq_len: 256

